### ISSUE TITLE
Question about flexibility

### ISSUE THREAD

**Issue by josephdburdick** [dburles/reactive-maps-example#1]
Hi @dburles, great plugin. I'm currently using this to show the user's geolocation but I'd also like to have a view where it shows all Markers in a collection. Do I need to create a different template file with a different map options reference or is there a way to make this act more like a component– being template agnostic and the data-context changes the behavior? Let me know how you would approach this. Thanks!

**Comment by josephdburdick** [comment]
Or... would you take the approach of turning the map into a meteor blaze component (https://github.com/peerlibrary/meteor-blaze-components)?

**Comment by dburles** [comment]
hey @josephdburdick I would create distinct maps for each.

**Comment by josephdburdick** [comment]
Ok thanks!
