### ISSUE TITLE
self. auotrun makes the map to blinck and unexpected recurssive helper calling

### ISSUE THREAD

**Issue by mahiagit** [dburles/reactive-maps-example#3]
Hi,

I have reactive map working great.
I have a new requirement. Have to show markers on the click on some element in page. i am successful it by doing the following
on click event i create the data as per which marker to be reflect and save in session.
this session is checked in the on created of this template and this.autorun makes it to function as desired.
It works great in the Chrome.
But in Firefox the helper is called again and again and the map remain blink. even this behaviour is also noticed in the ios and Android App

Kindly suggest

**Comment by dburles** [comment]
@mahiagit I think I would need to see a reproduction to help you further with that. It sounds like it's most likely an issue with your code somewhere.  http://stackoverflow.com/help/mcve

**Comment by mahiagit** [comment]
Thanks fort your reply. In the mean time I figure out the problem.

The Geolocation.latLng() after the self.autorun make the helper to call again and again in the firefox environment. so i put this outside the self.autorun function and the things work fine as expected.
The strange behavior of  self.autorun and Geolocation.latLng() makes the things blinking in my case but anyway i figured out the things and fixed.

Thanks for your help. i will be thankful if you throw some light why the same result of Geolocation.latLng() makes the helper call again ans again.

**Comment by dburles** [comment]
Oh the reason why it is called many times is that it's a reactive function. It will return a new result any time there is a variation in your current coordinates if it's contained within an autorun.

**Comment by mahiagit** [comment]
But there is no variation it is giving the same result (current location lat , lng)and still the auturun function/ methood behaves as discussed. I think it should listen when there is dependent value or session values changes but it becomes reactive on the same result value. Also it only did so in the Firefox only and in chrome and safari works fine

**Comment by dburles** [comment]
I think that's just just how the browser API works. You could write a check within the autorun to make sure the value has actually changed before taking action and updating the map. Check the source to see what's going on https://github.com/meteor/mobile-packages/blob/master/packages/mdg:geolocation/geolocation.js

**Comment by mahiagit** [comment]
Agreed with all this but the only question stucks in mind why the deviation only in one browser and sometimes in the App. Hope I am right regarding the behavior of self.autorun.

**Comment by dburles** [comment]
It might be just that the geolocation API differs slightly on firefox? I'm not entirely sure! Good luck with your app

**Comment by mahiagit** [comment]
Thanks for your valuable input. it means a lot. Have great time.
